task: multiclass
exp: cinc_ssl_simclr
method: simclr

training:
  epochs: 1000
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 1024
  input_length: 1250
  fs: 125  # Sampling frequency
  warmup_steps: 5
  temp: 0.07

model:
  num_classes: 4  # Number of classes
  input_channels: 1 # Number of input channel
  backbone: 'resnet1d18'  # Model backbone
  projection_dim: 128 # Projection dimensionality for linear head

evaluation:
  metric: 'f1'  # Evaluation metric: 'f1', 'auc', or others
  mode: 'linear'  # 'linear' or 'ft' (fine-tuning)
  multiclass: True  # True for multi-class, False for multi-label
  loss: BSCE

data:
  data_path: 'data/'
  group_indices: [4]  # Indices of data groups for training/validation/testing
  group_number: 5

device:
  use_cuda: True
  cuda_device: 'cuda:0'